// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZhB8uLI6krlz0M6tkUKnZsRJcY3xYw9k',
    appId: '1:741104919766:android:ef4075b3370d44ef0d5577',
    messagingSenderId: '741104919766',
    projectId: 'vitasnap-d5c7d',
    storageBucket: 'vitasnap-d5c7d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8qp8jR91v_TsabeO0wIt0JYxLdHG5438',
    appId: '1:741104919766:ios:5b9a2188df99073d0d5577',
    messagingSenderId: '741104919766',
    projectId: 'vitasnap-d5c7d',
    storageBucket: 'vitasnap-d5c7d.firebasestorage.app',
    androidClientId: '741104919766-fdosrsgs8jvnv2rptkmod1k2rpqsfjd4.apps.googleusercontent.com',
    iosClientId: '741104919766-r9fr8k9jkuohiiomjl7hoh5kl9v6v662.apps.googleusercontent.com',
    iosBundleId: 'com.mrizwantech.vitasnap',
  );
}
